var:
  isu1:
    tasks:
      - isu/isu1.yml
      # - isu/isu_add.yml
      - isu/delve.yml
    other:
      - common/common.yml
      # - monitoring/fluent-bit.yml
      # - monitoring/node_exporter.yml
      - other/alp.yml
      # - other/collect.yml
      - other/graphviz.yml
      - other/mysql.yml
      - other/netdata.yml
      - other/nginx.yml
      - other/parameter.yml
      - other/percona.yml
      # - other/redis.yml
  isu2:
    tasks:
    other:
  isu3:
    tasks:
    other:
