- name: isu1
  hosts: isu1
  gather_facts: false
  user: ubuntu
  become: true
  max_fail_percentage: 0
  vars_files:
    - ../env.yml
    - ../vars.yml
  tasks:
    - include_tasks: "../tasks/{{ item }}"
      with_items: "{{ var.isu1.other }}"
      when: var.isu1.other
    - include_tasks: "../tasks/{{ item }}"
      with_items: "{{ var.isu1.tasks }}"
      when: var.isu1.tasks
