name: "isu2"
on:
  workflow_dispatch:
jobs:
  Ansible2:
    name: "Ansible2 Job"
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Run playbook
        uses: dawidd6/action-ansible-playbook@v2
        with:
          playbook: playbooks/isu2.yml
          directory: ./ansible
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          inventory: |
            [isu2]
            ${{ vars.HOST2 }}
          options: |
            --inventory .hosts
