name: "isu3"
on:
  workflow_dispatch:
jobs:
  Ansible3:
    name: "Ansible3 Job"
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Run playbook
        uses: dawidd6/action-ansible-playbook@v2
        with:
          playbook: playbooks/isu3.yml
          directory: ./ansible
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          inventory: |
            [isu3]
            ${{ vars.HOST3 }}
          options: |
            --inventory .hosts
